"use client";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { trend, yearly } from "@/lib/demo-data"; import { money } from "@/lib/utils";
const tooltip={borderRadius:12,border:"1px solid #e2e8f0",boxShadow:"0 8px 25px #0001"};
export function DonationTrend({annual=false}:{annual?:boolean}){const data=annual?yearly:trend;return <ResponsiveContainer width="100%" height={280}><AreaChart data={data}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#0d7c66" stopOpacity={.35}/><stop offset="95%" stopColor="#0d7c66" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="3 3" opacity={.3}/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={v=>`${v/1000}k`}/><Tooltip formatter={(v:number)=>money(v)} contentStyle={tooltip}/><Area dataKey="donations" type="monotone" stroke="#0d7c66" strokeWidth={3} fill="url(#fill)"/></AreaChart></ResponsiveContainer>}
const split=[{name:"Festival",value:18500,color:"#0d7c66"},{name:"Charity",value:6500,color:"#e0a82e"},{name:"Maintenance",value:4200,color:"#4f86c6"},{name:"Temple",value:2800,color:"#9c6ade"},{name:"Misc.",value:1200,color:"#e56b6f"}];
export function ExpensePie(){return <div className="grid items-center sm:grid-cols-[1fr_150px]"><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={split} dataKey="value" innerRadius={62} outerRadius={92} paddingAngle={4}>{split.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip formatter={(v:number)=>money(v)} contentStyle={tooltip}/></PieChart></ResponsiveContainer><div className="space-y-2">{split.map(x=><div className="flex items-center justify-between gap-4 text-xs" key={x.name}><span><i className="mr-2 inline-block size-2 rounded-full" style={{background:x.color}}/>{x.name}</span><b>{money(x.value)}</b></div>)}</div></div>}
const pending=[{name:"Karthik",amount:12000},{name:"Ganesh",amount:7000},{name:"Bala",amount:3500},{name:"Prabhu",amount:2000}];
export function PendingBar(){return <ResponsiveContainer width="100%" height={250}><BarChart data={pending} layout="vertical"><CartesianGrid horizontal={false} strokeDasharray="3 3" opacity={.3}/><XAxis type="number" hide/><YAxis dataKey="name" type="category" axisLine={false} tickLine={false} width={65}/><Tooltip formatter={(v:number)=>money(v)} contentStyle={tooltip}/><Bar dataKey="amount" fill="#e0a82e" radius={[0,8,8,0]} barSize={22}/></BarChart></ResponsiveContainer>}
