import * as XLSX from "xlsx"; import { createClient } from "@supabase/supabase-js"; import { resolve } from "node:path";
type Row=Record<string,unknown>; const file=resolve(process.argv[2]||"AB Sandha_nankodai Sheet.xlsx");
const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY");
const supabase=createClient(url,key,{auth:{persistSession:false}}),book=XLSX.readFile(file,{cellDates:true});
const text=(r:Row,...keys:string[])=>{for(const k of keys){const v=r[k];if(v!==undefined&&v!==null&&String(v).trim())return String(v).trim()}return null};
const amount=(v:unknown)=>Number(String(v??0).replace(/[^0-9.-]/g,""))||0;
async function run(){const memberSheet=book.Sheets[book.SheetNames.find(x=>/member/i.test(x))||book.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Row>(memberSheet,{defval:null});const memberMap=new Map<string,string>();for(const r of rows){const name=text(r,"Member Name","Name","member_name");if(!name)continue;const {data,error}=await supabase.from("members").upsert({member_name:name,family_name:text(r,"Family","Family Name"),phone:text(r,"Phone","Mobile"),status:text(r,"Status")?.toLowerCase()||"active",annual_commitment:amount(r["Annual Commitment"]??r["Sandha Amount"])},{onConflict:"member_name"}).select("id").single();if(error)throw error;memberMap.set(name.toLowerCase(),data.id)}
for(const sheetName of book.SheetNames){if(/member/i.test(sheetName))continue;const year=Number(sheetName.match(/20\d{2}/)?.[0])||new Date().getFullYear();for(const r of XLSX.utils.sheet_to_json<Row>(book.Sheets[sheetName],{defval:null})){const name=text(r,"Member Name","Name","member_name"),value=amount(r["Amount"]??r["Donation"]??r["Sandha"]);if(!name||!value)continue;const member_id=memberMap.get(name.toLowerCase());if(!member_id){console.warn(`Skipped unknown member: ${name}`);continue}const {error}=await supabase.from("donations").insert({member_id,donation_year:year,amount:value,donation_type:text(r,"Type","Donation Type")||"Sandha",payment_date:text(r,"Payment Date","Date"),remarks:text(r,"Remarks","Notes")});if(error)throw error}}
console.log(`Import complete: ${memberMap.size} members processed.`)}run().catch(e=>{console.error(e);process.exit(1)});
